### ISSUE TITLE
[package name problem]

### ISSUE THREAD

**Issue by IIpho3nix** [TheF1xer/GateClient#2]
I noticed you used com.thef1xer as your package name and you dont own the domain i suggest looking at naming conventions https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by TheF1xer** [comment]
I have noticed that but I don't own a domain at this moment and that guide doesn't specify what should be done in those cases. Do you know what package name I should use?

**Comment by IIpho3nix** [comment]
ı wish i could answer that question but i cant since i dont accutly know too but this may help mybea

https://stackoverflow.com/questions/12535798/whats-the-convention-for-java-package-names-without-a-domain-association

**Comment by TheF1xer** [comment]
Thanks, I probably won't change it until I really know what I should do, but I'll have this in mind.
