### ISSUE TITLE
Features :D

### ISSUE THREAD

**Issue by ghost** [TheF1xer/GateClient#9]
hud editor, menu dragging, optimization for notebook extension and other montiors

**Comment by TheF1xer** [comment]
Hello, a HUD editor is something I've been thinking about for a while and problably will come eventually. I would like to know what are the optimizations for notebook you are talking about. Could you give me an example? Or maybe are there other mods that do this?

**Comment by ghost** [comment]
> Hello, a HUD editor is something I've been thinking about for a while and problably will come eventually. I would like to know what are the optimizations for notebook you are talking about. Could you give me an example? Or maybe are there other mods that do this?

I meant the screen resolution

**Comment by TheF1xer** [comment]
Oh, to make the HUD and Click GUI work properly, have to set your GUI Scale to normal ad it will render properly
